### ISSUE TITLE
Meshery Adapter for Cilium Crash on Boot

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-cilium#101]
#### Current Behavior
The Meshery Adapter for Cilium crashes on boot with the following error logs.

#### Screenshots/Logs
```
meshery-meshery-cilium-1        | time="2023-01-14T00:13:33Z" level=info msg="Registering static workloads completed" app=cilium-adapter
meshery-meshery-cilium-1        | time="2023-01-14T00:13:33Z" level=info msg="lstat /templates/oam/traits: no such file or directory" app=cilium-adapter
meshery-meshery-cilium-1        | panic: interface conversion: error is *fs.PathError, not *errors.Error
meshery-meshery-cilium-1        |
meshery-meshery-cilium-1        | goroutine 72 [running]:
meshery-meshery-cilium-1        | github.com/layer5io/meshkit/errors.GetCode({0x25ee0c0?, 0xc00050e750?})
meshery-meshery-cilium-1        | 	/go/pkg/mod/github.com/layer5io/meshkit@v0.6.16/errors/errors.go:89 +0x90
meshery-meshery-cilium-1        | github.com/layer5io/meshkit/logger.(*Logger).Error(0xc00049a0c0, {0x25ee0c0?, 0xc00050e750})
meshery-meshery-cilium-1        | 	/go/pkg/mod/github.com/layer5io/meshkit@v0.6.16/logger/logger.go:71 +0x9f
meshery-meshery-cilium-1        | main.registerCapabilities({0x228a92d, 0x5}, {0x2610b38, 0xc00049a0c0})
meshery-meshery-cilium-1        | 	/github.com/meshery/meshery-cilium/main.go:165 +0x32a
meshery-meshery-cilium-1        | created by main.main
meshery-meshery-cilium-1        | 	/github.com/meshery/meshery-cilium/main.go:112 +0x63b
meshery-meshery-cilium-1 exited with code 2
```

#### Environment

- **Host OS:** Mac 
- **Platform:** Docker 
- **Meshery Adapter for Cilium Version:** edge-latest
- **Meshery Server Version:** stable-v0.6.43
- **Meshery Client Version:** stable-v0.6.43

---
#### Contributor [Guides](https://docs.meshery.io/project/contributing) and Resources
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by leecalcote** [comment]
Fixed in v0.6.3
